### PR TITLE
Read key from KEY_ENV if available

### PR DESCRIPTION
**Pull request by ribose-jeffreylau**
Mainly as food for thought for https://github.com/rnpgp/rnp/pull/1564

I admit it's quite hacky!

### CODE REVIEW

**Review by ni4 — COMMENTED** [review]
I would also update check on the line 236, about the default key. GitHub doesn't seem to allow me to add comment there )

**Comment by ronaldtse** [comment]
@ribose-jeffreylau are we ready to merge this? Thanks!

**Comment by ni4** [comment]
@ribose-jeffreylau JFYI: as PR #1573 is now merged, you may use `rnp --keyfile env:KEY_ENV` to read a key.

**Comment by ribose-jeffreylau** [comment]
Thanks @ni4, I think we can just close this PR :)

**Pull request closed without merging**
